services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: movie-app
    volumes:
      - ./data/static:/opt/app/staticfiles:rw
      - ./data/media:/opt/app/media:rw
      - ./data/logs:/var/log/:rw
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - db_network
      - web_network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: movie-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data/static:/var/www/static:ro
      - ./data/media:/var/www/media:ro
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - app
    networks:
      - web_network
    ports:
      - "80:80"

  db:
    image: postgres:15
    container_name: theatre-db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8080:8080"
    volumes:
      - ./api_data/openapi.yaml:/swagger.yaml
    environment:
      SWAGGER_JSON: /swagger.yaml
    depends_on:
      - app
    networks:
      - web_network


networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

