# Generated by Django 4.2.11 on 2024-12-24 21:14

from django.db import migrations, models
import movies.utils


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=movies.utils.person_photo_path, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(choices=[('actor', 'actor'), ('director', 'director'), ('writer', 'writer')], default='actor', max_length=10, verbose_name='role'),
        ),
    ]
